# Generated by Django 4.2.16 on 2024-10-06 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('exam_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('exam_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_times', to='exam_location.examlocation')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.JSONField()),
                ('month', models.CharField(max_length=50)),
                ('exam_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='exam_location.examlocation')),
            ],
        ),
    ]
