# Generated by Django 4.2.16 on 2024-10-07 23:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exam_location', '0002_alter_calendar_days_alter_calendar_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=83),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='month',
            field=models.CharField(choices=[('JAN', 'JANEIRO'), ('FEV', 'FEVEREIRO'), ('MAR', 'MARÇO'), ('ABR', 'ABRIL'), ('MAI', 'MAIO'), ('JUN', 'JUNHO'), ('JUL', 'JULHO'), ('AGO', 'AGOSTO'), ('SET', 'SETEMBRO'), ('OUT', 'OUTUBRO'), ('NOV', 'NOVEMBRO'), ('DEZ', 'DEZEMBRO')], max_length=3),
        ),
    ]
