# Generated by Django 4.2.16 on 2024-11-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_remove_exam_name2'),
        ('exam_location', '0004_examscheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='examscheduled',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exams.exam'),
            preserve_default=False,
        ),
    ]
