# Generated by Django 4.2.16 on 2024-11-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_location', '0005_examscheduled_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examscheduled',
            name='calendar',
        ),
        migrations.AddField(
            model_name='examscheduled',
            name='day',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
