# Generated by Django 4.2.16 on 2024-11-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_location', '0006_remove_examscheduled_calendar_examscheduled_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='examscheduled',
            name='month',
            field=models.CharField(choices=[('JAN', 'JANEIRO'), ('FEV', 'FEVEREIRO'), ('MAR', 'MARÇO'), ('ABR', 'ABRIL'), ('MAI', 'MAIO'), ('JUN', 'JUNHO'), ('JUL', 'JULHO'), ('AGO', 'AGOSTO'), ('SET', 'SETEMBRO'), ('OUT', 'OUTUBRO'), ('NOV', 'NOVEMBRO'), ('DEZ', 'DEZEMBRO')], default='JAN', max_length=3),
            preserve_default=False,
        ),
    ]
