# Generated by Django 4.2.16 on 2024-11-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_location', '0007_examscheduled_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('schedule_time', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
