# Generated by Django 4.2.16 on 2024-10-06 12:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0003_rename_class_id_exam_class1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Subjects',
        ),
        migrations.RenameModel(
            old_name='Users_classes',
            new_name='Users_subjects',
        ),
    ]
