# Generated by Django 4.2.16 on 2024-10-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_rename_class_subjects_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='class1',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='users_subjects',
            old_name='class1',
            new_name='subject',
        ),
    ]
