# Generated by Django 4.2.16 on 2024-10-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_rename_class1_exam_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='name',
        ),
    ]
