# Generated by Django 4.2.16 on 2024-10-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='name2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
