# Generated by Django 4.2.16 on 2024-10-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exam_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='name2',
        ),
    ]
