# Generated by Django 4.2.16 on 2024-10-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_remove_exam_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.BigIntegerField(max_length=255),
        ),
    ]
