# Generated by Django 4.2.16 on 2024-10-10 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_alter_exam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='name2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.subjects'),
        ),
    ]
