# Generated by Django 4.2.16 on 2024-10-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_exam_name2_alter_exam_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='name2',
        ),
    ]
